"""empty message

Revision ID: 3b3580516928
Revises: f8064550049a
Create Date: 2023-03-05 17:53:22.568290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3580516928'
down_revision = 'f8064550049a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_metrics_table', type_='foreignkey')
    op.create_foreign_key(None, 'project_metrics_table', 'user_account_table', ['userid'], ['id'])
    op.add_column('user_account_table', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user_account_table', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account_table', sa.Column('userid', sa.INTEGER(), nullable=False))
    op.drop_column('user_account_table', 'id')
    op.drop_constraint(None, 'project_metrics_table', type_='foreignkey')
    op.create_foreign_key(None, 'project_metrics_table', 'user_account_table', ['userid'], ['userid'])
    # ### end Alembic commands ###
